# This file provides instructions for packaging.

@prefix : <http://ontologi.es/doap-deps#>.

`Alt-common-sense-TOBYINK`
	:runtime-requirement    [ :on "perl 5.006"^^:CpanId ];
	:test-requirement       [ :on "Test::More"^^:CpanId ];
	:develop-recommendation [ :on "Dist::Inkt::Profile::TOBYINK"^^:CpanId ];
	.

